KEY_RELEASE_SUFFIX = '_release'
KEY_UNDEFINED = 'None'

KEY_PYNPUT_PYAUTOGUI = {
    "\t": "\t",
    "\n": "\n",
    "\r": "\r",
    " ": " ",
    "!": "!",
    '"': '"',
    "#": "#",
    "$": "$",
    "%": "%",
    "&": "&",
    "'": "'",
    "(": "(",
    ")" : ")",
    "*": "*",
    "+": "+",
    ",": ",",
    "-": "-",
    ".": ".",
    "/": "/",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    ":": ":",
    ";": ";",
    "<": "<",
    "=": "=",
    ">": ">",
    "?": "?",
    "@": "@",
    "[": "[",
    "\\": "\\",
    "]": "]",
    "^": "^",
    "_": "_",
    "`": "`",
    "a": "a",
    "b": "b",
    "c": "c",
    "d": "d",
    "e": "e",
    "f": "f",
    "g": "g",
    "h": "h",
    "i": "i",
    "j": "j",
    "k": "k",
    "l": "l",
    "m": "m",
    "n": "n",
    "o": "o",
    "p": "p",
    "q": "q",
    "r": "r",
    "s": "s",
    "t": "t",
    "u": "u",
    "v": "v",
    "w": "w",
    "x": "x",
    "y": "y",
    "z": "z",
    "{": "{",
    "|": "|",
    "}": "}",
    "~": "~",
    "accept": "accept",
    "add": "add",
    "Key.alt": "alt",
    "altleft": "altleft",
    "altright": "altright",
    "apps": "apps",
    "Key.backspace": "backspace",
    "browserback": "browserback",
    "browserfavorites": "browserfavorites",
    "browserforward": "browserforward",
    "browserhome": "browserhome",
    "browserrefresh": "browserrefresh",
    "browsersearch": "browsersearch",
    "browserstop": "browserstop",
    "Key.caps_lock": "capslock",
    "clear": "clear",
    "convert": "convert",
    "Key.ctrl_l": "ctrl",
    "ctrlleft": "ctrlleft",
    "ctrlright": "ctrlright",
    "decimal": "decimal",
    "del": "del",
    "delete": "delete",
    "divide": "divide",
    "Key.down": "down",
    "end": "end",
    "Key.enter": "enter",
    "Key.esc": "esc",
    "escape": "escape",
    "execute": "execute",
    "Key.f1": "f1",
    "Key.f10": "f10",
    "Key.f11": "f11",
    "Key.f12": "f12",
    "Key.f13": "f13",
    "Key.f14": "f14",
    "Key.f15": "f15",
    "Key.f16": "f16",
    "Key.f17": "f17",
    "Key.f18": "f18",
    "Key.f19": "f19",
    "Key.f2": "f2",
    "Key.f20": "f20",
    "Key.f21": "f21",
    "Key.f22": "f22",
    "Key.f23": "f23",
    "Key.f24": "f24",
    "Key.f3": "f3",
    "Key.f4": "f4",
    "Key.f5": "f5",
    "Key.f6": "f6",
    "Key.f7": "f7",
    "Key.f8": "f8",
    "Key.f9": "f9",
    "final": "final",
    "fn": "fn",
    "hanguel": "hanguel",
    "hangul": "hangul",
    "hanja": "hanja",
    "help": "help",
    "home": "home",
    "insert": "insert",
    "junja": "junja",
    "kana": "kana",
    "kanji:": "kanji",
    "launchapp1": "launchapp1",
    "launchapp2": "launchapp2",
    "launchmail": "launchmail",
    "launchmediaselect": "launchmediaselect",
    "Key.left": "left",
    "modechange": "modechange",
    "multiply": "multiply",
    "nexttrack": "nexttrack",
    "nonconvert": "nonconvert",
    "num0": "num0",
    "num1": "num1",
    "num2": "num2",
    "num3": "num3",
    "num4": "num4",
    "num5": "num5",
    "num6": "num6",
    "num7": "num7",
    "num8": "num8",
    "num9": "num9",
    "numlock": "numlock",
    "pagedown": "pagedown",
    "pageup": "pageup",
    "pause": "pause",
    "pgdn": "pgdn",
    "pgup": "pgup",
    "playpause": "playpause",
    "prevtrack": "prevtrack",
    "print": "print",
    "printscreen": "printscreen",
    "prntscrn": "prntscrn",
    "prtsc": "prtsc",
    "prtscr": "prtscr",
    "return": "return",
    "Key.right": "right",
    "scrolllock": "scrolllock",
    "select": "select",
    "separator": "separator",
    "Key.shift": "shift",
    "shiftleft": "shiftleft",
    "shiftright": "shiftright",
    "sleep": "sleep",
    "Key.space": "space",
    "stop": "stop",
    "subtract": "subtract",
    "Key.tab": "tab",
    "Key.up": "up",
    "volumedown": "volumedown",
    "volumemute": "volumemute",
    "volumeup": "volumeup",
    "win": "win",
    "winleft": "winleft",
    "winright": "winright",
    "yen": "yen",
    "command": "command",
    "option": "option",
    "optionleft": "optionleft",
    "optionright": "optionright",
}

MOUSE_KEY_PREFIX = 'Mouse.'
MOUSE_MOVE_LEFT = MOUSE_KEY_PREFIX + 'left'
MOUSE_MOVE_RIGHT = MOUSE_KEY_PREFIX + 'right'
MOUSE_STOP_X = MOUSE_KEY_PREFIX + 'stop_x'
MOUSE_MOVE_UP = MOUSE_KEY_PREFIX + 'up'
MOUSE_MOVE_DOWN = MOUSE_KEY_PREFIX + 'down'
MOUSE_STOP_Y = MOUSE_KEY_PREFIX + 'stop_y'

NN_SOUND_SPECT_INPUT_DIM = (96, 96)

NN_MODEL_SINGLE = 10001
NN_MODEL_LSTM = 10002
NN_SHUFFLE_BUFFER_SIZE = 500

PATH_SCREENSHOTS = 'var/screenshots/'
PATH_TEMPLATES = 'var/templates/'
PATH_NN_WEIGHTS = 'var/nn_weights/'